using System;
using System.IO;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Windows.Forms;
using System.Runtime.InteropServices;
using VisibleCellsPaste;
class FunctionalTests {
 static dynamic app,sheet,book; static string output;static int passed,failed;static List<string> results=new List<string>();
 static ClipboardSnapshot Source(params CellValue[] items){return new ClipboardSnapshot("SyntheticTyped",0,items.Length,1,true,items,"test-only");}
 static void Check(bool yes,string message){if(!yes)throw new Exception(message);}
 static void Test(string id,Action body){var sw=Stopwatch.StartNew();try{Reset();body();passed++;results.Add(id+" PASS "+sw.ElapsedMilliseconds+"ms");}catch(Exception e){failed++;results.Add(id+" FAIL "+e.ToString());}File.WriteAllLines(output,results,Encoding.UTF8);Console.WriteLine(results[results.Count-1]);}
 static void Reset(){app.EnableEvents=true;app.Calculation=-4105;app.ScreenUpdating=true;sheet.Range["A1:J100"].Clear();sheet.Range["A1:J100"].UnMerge();sheet.Rows["1:100"].Hidden=false;sheet.Columns["A:J"].Hidden=false;foreach(dynamic table in sheet.ListObjects)table.Unlist();try{sheet.Unprotect();}catch{}sheet.Range["E2:E8"].NumberFormat="0.00";sheet.Range["E2:E8"].Value2=777.0;sheet.Range["E2:E8"].Interior.Color=65535;sheet.Range["E2:E8"].Font.Bold=true;sheet.Range["E2:E8"].Select();Application.DoEvents();}
 static object V(string addr){return sheet.Range[addr].Value2;}
 static string Fingerprint(string exclude){var b=new StringBuilder();for(int r=1;r<=12;r++)for(int c=1;c<=8;c++){string address=(string)sheet.Cells[r,c].Address;if(exclude.Contains("|"+address+"|"))continue;var s=ExcelEngine.ReadCell((object)sheet,r,c);b.Append(address).Append('/').Append(s.Formula).Append('/').Append(s.FormulaValue).Append('/').Append(s.Formula?"formula":s.Value.Kind.ToString()).Append('/').Append(s.Formula?null:s.Value.Value).Append('/').Append(s.Format).Append('/').Append(sheet.Cells[r,c].Interior.Color).Append('/').Append(sheet.Cells[r,c].Font.Bold).Append('/').Append(sheet.Rows[r].Hidden).Append(';');}return b.ToString();}
 static void SetVisible(){sheet.Rows["3:4"].Hidden=true;sheet.Rows["6:7"].Hidden=true;sheet.Range["E3"].Formula2="=E2*2";}
 static void Reject(ExcelEngine e,ClipboardSnapshot src){string before=Fingerprint("");bool threw=false;try{e.Prepare(src);}catch{threw=true;}Check(threw,"Expected validation refusal");Check(before==Fingerprint(""),"Refusal changed cells");}
 [STAThread]static int Main(string[] args){output=args[1];app=ExcelProbe.Attach(Int32.Parse(args[0]));book=app.ActiveWorkbook;if(!((string)book.Name).StartsWith("VCP-"))throw new Exception("Owned VCP fixture required");sheet=book.Worksheets[1];sheet.Activate();bool synthetic=args.Length>2&&args[2]=="--synthetic-regression";ClipboardSnapshot clip=synthetic?Source(CellValue.Number(85),CellValue.Text("00123"),CellValue.Empty(),CellValue.Text("한글\n줄바꿈"),CellValue.Empty()):ClipboardReader.ReadSnapshot(Convert.ToInt32((object)app.CutCopyMode));results.Add((synthetic?"Synthetic typed regression items=":"M0 live XML items=")+clip.Items.Count+" kinds="+String.Join(",",System.Linq.Enumerable.Select(clip.Items,x=>x.Kind.ToString()))+" evidence="+clip.Evidence);Console.WriteLine(results[0]);
 Test(synthetic?"Typed-five-regression":"M0-clipboard-to-owned-Excel",delegate{sheet.Range["E2:E6"].Select();using(var e=new ExcelEngine(app)){e.Apply(e.Prepare(clip),null,null);Check((double)V("E2")==85,"number");Check((string)V("E3")=="00123","string");Check(V("E4")==null&&V("E6")==null,"empty positions");Check((string)V("E5")=="한글\n줄바꿈","line break");}});
 Test("D01-R02-U01-U15",delegate{SetVisible();string outside=Fingerprint("|$E$2|$E$5|$E$8|");using(var e=new ExcelEngine(app)){var p=e.Prepare(Source(CellValue.Number(85),CellValue.Number(90),CellValue.Number(78)));e.Apply(p,null,null);Check((double)V("E2")==85&&(double)V("E5")==90&&(double)V("E8")==78,"order");Check(outside==Fingerprint("|$E$2|$E$5|$E$8|"),"hidden/outside preservation");e.UndoLast();Check((double)V("E2")==777&&(double)V("E5")==777,"undo");}});
 Test("D04-D05-D06-U16",delegate{sheet.Range["E2:E4"].Select();using(var e=new ExcelEngine(app)){e.Apply(e.Prepare(Source(CellValue.Number(1),CellValue.Number(2),CellValue.Number(3))),null,null);Reject(e,Source(CellValue.Number(7)));e.UndoLast();Check((double)V("E2")==777,"failed validate invalidated prior undo");}});
 Test("D07-D09-D11-D14-D15-D16-U02",delegate{sheet.Range["E2:E9"].Select();sheet.Range["E2"].Formula2="=10+5";using(var e=new ExcelEngine(app)){var p=e.Prepare(Source(CellValue.Empty(),CellValue.Text("00123"),CellValue.Text("12345678901234567890123"),CellValue.Text("=1+1"),CellValue.Text("한글\t😀\n "),CellValue.Error(2042),CellValue.Text("#N/A"),CellValue.Text("")));e.Apply(p,null,null);Check(!(bool)sheet.Range["E5"].HasFormula&&(string)V("E5")=="=1+1","formula injection");Check(ExcelEngine.ReadCell((object)sheet,7,5).Value.Kind==CellValueKind.Error,"error type");e.UndoLast();Check((string)sheet.Range["E2"].Formula2=="=10+5","formula restore");}});
 Test("D03-R08",delegate{sheet.Range["E5"].Select();string before=Fingerprint("|$E$5|");using(var e=new ExcelEngine(app)){e.Apply(e.Prepare(Source(CellValue.Boolean(true))),null,null);}Check((bool)V("E5"),"bool");Check(before==Fingerprint("|$E$5|"),"single SpecialCells bounds");});
 Test("R06-entire-column",delegate{sheet.Range["E:E"].Select();using(var e=new ExcelEngine(app))Reject(e,Source(CellValue.Number(1)));});
 Test("R07-multiple-areas",delegate{app.Union(sheet.Range["E2"],sheet.Range["E5"]).Select();using(var e=new ExcelEngine(app))Reject(e,Source(CellValue.Number(1),CellValue.Number(2)));});
 Test("R04-zero-visible",delegate{sheet.Rows["2:8"].Hidden=true;using(var e=new ExcelEngine(app))Reject(e,Source(CellValue.Number(1)));});
 Test("R09-merge",delegate{sheet.Range["E2:F2"].Merge();sheet.Range["E2"].Select();using(var e=new ExcelEngine(app))Reject(e,Source(CellValue.Number(1)));});
 Test("R09-protected",delegate{sheet.Range["E2"].Select();sheet.Protect();try{using(var e=new ExcelEngine(app))Reject(e,Source(CellValue.Number(1)));}finally{sheet.Unprotect();}});
 Test("R10-spill",delegate{sheet.Range["G2"].Formula2="=SEQUENCE(3)";sheet.Range["G3"].Select();using(var e=new ExcelEngine(app))Reject(e,Source(CellValue.Number(1)));});
 Test("R13-validation",delegate{sheet.Range["E2"].Select();sheet.Range["E2"].Validation.Add(1,1,1,"1","10");using(var e=new ExcelEngine(app))Reject(e,Source(CellValue.Number(1)));});
 Test("U08-write-failure",delegate{SetVisible();string before=Fingerprint("");using(var e=new ExcelEngine(app)){e.FailAfterWrites=2;bool rejected=false;try{e.Apply(e.Prepare(Source(CellValue.Number(1),CellValue.Number(2),CellValue.Number(3))),null,null);}catch(InvalidOperationException){rejected=true;}Check(rejected&&e.LastOutcome=="rolled-back","failure outcome");Check(before==Fingerprint(""),"rollback");}});
 Test("U09-recovery-failure",delegate{SetVisible();using(var e=new ExcelEngine(app)){e.FailAfterWrites=2;e.FailRecoveryAt=0;bool blocked=false;try{e.Apply(e.Prepare(Source(CellValue.Number(1),CellValue.Number(2),CellValue.Number(3))),null,null);}catch(RecoveryException ex){blocked=ex.FailedAddresses.Length>0;}Check(blocked&&e.RecoveryRequired,"recovery required");Reject(e,Source(CellValue.Number(1),CellValue.Number(2),CellValue.Number(3)));}});
 Test("U11-write-cancel",delegate{SetVisible();string before=Fingerprint("");using(var e=new ExcelEngine(app)){e.CancelAfterWrite=true;try{e.Apply(e.Prepare(Source(CellValue.Number(1),CellValue.Number(2),CellValue.Number(3))),null,null);}catch(InvalidOperationException){}Check(before==Fingerprint(""),"cancel rollback");}});
 Test("U12-original-global-state",delegate{sheet.Range["E2"].Select();app.EnableEvents=false;app.Calculation=-4135;app.ScreenUpdating=false;app.StatusBar="VCP prior";using(var e=new ExcelEngine(app)){e.Apply(e.Prepare(Source(CellValue.Number(1))),null,null);Check(!(bool)app.EnableEvents&&(int)app.Calculation==-4135&&!(bool)app.ScreenUpdating&&(string)app.StatusBar=="VCP prior","globals restored");bool refused=false;try{e.UndoLast();}catch{refused=true;}Check(refused,"disabled events undo unsafe");}app.EnableEvents=true;app.ScreenUpdating=true;app.Calculation=-4105;app.StatusBar=false;});
 Test("U03-user-edit",delegate{sheet.Range["E2"].Select();using(var e=new ExcelEngine(app)){e.Apply(e.Prepare(Source(CellValue.Number(1))),null,null);sheet.Range["E2"].Value2=42;Application.DoEvents();bool refused=false;try{e.UndoLast();}catch{refused=true;}Check(refused&&(double)V("E2")==42,"edit conflict");}});
 Test("U04-row-insert",delegate{sheet.Range["E2:E4"].Select();using(var e=new ExcelEngine(app)){e.Apply(e.Prepare(Source(CellValue.Number(1),CellValue.Number(1),CellValue.Number(1))),null,null);sheet.Rows["2:2"].Insert();Application.DoEvents();bool refused=false;try{e.UndoLast();}catch{refused=true;}Check(refused,"row insert conflict");}});
 Test("R11-table-value-R12-mixed",delegate{sheet.Range["E1"].Value2="Data";dynamic table=sheet.ListObjects.Add(1,sheet.Range["E1:E8"],Type.Missing,1);sheet.Range["E2:E4"].Select();using(var e=new ExcelEngine(app)){e.Apply(e.Prepare(Source(CellValue.Number(1),CellValue.Number(2),CellValue.Number(3))),null,null);Check((double)V("E4")==3,"table values");sheet.Range["E8"].Formula2="=1+2";Application.DoEvents();Reject(e,Source(CellValue.Number(1),CellValue.Number(2),CellValue.Number(3)));}table.Unlist();});
 results.Add("SUMMARY passed="+passed+" failed="+failed);File.WriteAllLines(output,results,Encoding.UTF8);Console.WriteLine(results[results.Count-1]);return failed==0?0:1;}
}
