using System;
using System.IO;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Windows.Forms;
using System.Runtime.InteropServices;
using VisibleCellsPaste;
class FunctionalTests {
 static dynamic app,sheet,book; static ComScope caseRefs; static string output;static int passed,failed;static List<string> results=new List<string>();
 static ClipboardSnapshot Source(params CellValue[] items){return new ClipboardSnapshot("SyntheticTyped",0,items.Length,1,true,items,"test-only");}
 static void Check(bool yes,string message){if(!yes)throw new Exception(message);}
 static dynamic Own(object value){return caseRefs.Own(value);}
 static dynamic R(string address){return Own((object)sheet.Range[address]);}
 static dynamic Rows(string address){dynamic rows=Own((object)sheet.Rows);return Own((object)rows[address]);}
 static dynamic Columns(string address){dynamic columns=Own((object)sheet.Columns);return Own((object)columns[address]);}
 static void Cleanup(string name,Action action){try{action();}catch(Exception error){failed++;results.Add("CLEANUP FAIL "+name+": "+error);}}
 static void Test(string id,Action body){var sw=Stopwatch.StartNew();caseRefs=new ComScope();try{Reset();body();passed++;results.Add(id+" PASS "+sw.ElapsedMilliseconds+"ms");}catch(Exception e){failed++;results.Add(id+" FAIL "+e.ToString());}finally{Cleanup("case references",delegate{caseRefs.Dispose();});caseRefs=null;}File.WriteAllLines(output,results,Encoding.UTF8);Console.WriteLine(results[results.Count-1]);}
 static void Reset(){app.EnableEvents=true;app.Calculation=-4105;app.ScreenUpdating=true;R("A1:J100").Clear();R("A1:J100").UnMerge();Rows("1:100").Hidden=false;Columns("A:J").Hidden=false;dynamic tables=Own((object)sheet.ListObjects);for(int i=(int)tables.Count;i>=1;i--)Own((object)tables[i]).Unlist();try{sheet.Unprotect();}catch{}R("E2:E8").NumberFormat="0.00";R("E2:E8").Value2=777.0;Own((object)R("E2:E8").Interior).Color=65535;Own((object)R("E2:E8").Font).Bold=true;R("E2:E8").Select();Application.DoEvents();}
 static object V(string addr){return R(addr).Value2;}
 static string Fingerprint(string exclude){var b=new StringBuilder();using(var refs=new ComScope()){dynamic cells=refs.Own((object)sheet.Cells),rows=refs.Own((object)sheet.Rows);for(int r=1;r<=12;r++)for(int c=1;c<=8;c++)using(var cellRefs=new ComScope()){dynamic cell=cellRefs.Own((object)cells[r,c]);string address=(string)cell.Address;if(exclude.Contains("|"+address+"|"))continue;var s=ExcelEngine.ReadCell((object)sheet,r,c);dynamic interior=cellRefs.Own((object)cell.Interior),font=cellRefs.Own((object)cell.Font),row=cellRefs.Own((object)rows[r]);b.Append(address).Append('/').Append(s.Formula).Append('/').Append(s.FormulaValue).Append('/').Append(s.Formula?"formula":s.Value.Kind.ToString()).Append('/').Append(s.Formula?null:s.Value.Value).Append('/').Append(s.Format).Append('/').Append(interior.Color).Append('/').Append(font.Bold).Append('/').Append(row.Hidden).Append(';');}}return b.ToString();}
 static void SetVisible(){Rows("3:4").Hidden=true;Rows("6:7").Hidden=true;R("E3").Formula2="=E2*2";}
 static void Reject(ExcelEngine e,ClipboardSnapshot src){string before=Fingerprint("");bool threw=false;try{using(var unexpected=e.Prepare(src)){} }catch{threw=true;}Check(threw,"Expected validation refusal");Check(before==Fingerprint(""),"Refusal changed cells");}
 static string StatusDescription(object value){return value==null?"<null>":value.GetType().AssemblyQualifiedName+" value=["+Convert.ToString(value,System.Globalization.CultureInfo.InvariantCulture)+"]";}
 static void CheckStatus(string stage,object expected){object actual=app.StatusBar;results.Add("  STATUS "+stage+" expected{"+StatusDescription(expected)+"} actual{"+StatusDescription(actual)+"}");Check(Object.Equals(actual,expected),"Exact StatusBar type/value not preserved at "+stage);}
 static void RestoreStatus(object prior){results.Add("  STATUS cleanup-before "+StatusDescription((object)app.StatusBar));ExcelEngine.RestoreStatusBar((object)app,prior);CheckStatus("cleanup-after",prior);}
 static void CheckSeededValues(string stage){Check((double)V("E2")==777&&(double)V("E5")==777&&(double)V("E8")==777,"Status regression cells not restored: "+stage);Check((string)R("E3").Formula2=="=E2*2","Status regression hidden formula changed: "+stage);}
 static void StatusBarOwnershipCase(){object original=app.StatusBar;try{foreach(object prior in new object[]{false,"FALSE"}){Reset();SetVisible();string kind=prior is bool?"BooleanFalse":"LiteralStringFALSE";if(prior is bool)app.StatusBar="";else app.StatusBar=prior;CheckStatus(kind+" starting control",prior);var source=Source(CellValue.Number(85),CellValue.Number(90),CellValue.Number(78));using(var engine=new ExcelEngine((object)app)){using(var prepared=engine.Prepare(source)){}CheckStatus(kind+" Prepare",prior);bool refused=false;try{using(var unexpected=engine.Prepare(Source(CellValue.Number(1),CellValue.Number(2)))){}}catch(ValidationException error){refused=error.Code=="VCP-COUNT-MISMATCH";}Check(refused,"Status regression expected exact count mismatch refusal");CheckStatus(kind+" refusal",prior);CheckSeededValues("refusal");engine.Apply(engine.Prepare(source),null,null);CheckStatus(kind+" Apply",prior);Check((double)V("E2")==85&&(double)V("E5")==90&&(double)V("E8")==78,"Status regression apply values");engine.UndoLast();CheckStatus(kind+" Undo",prior);CheckSeededValues("Undo");}
 using(var engine=new ExcelEngine((object)app)){engine.FailAfterWrites=2;bool rolledBack=false;try{engine.Apply(engine.Prepare(source),null,null);}catch(InvalidOperationException){rolledBack=engine.LastOutcome=="rolled-back";}Check(rolledBack,"Status regression write failure did not roll back");CheckStatus(kind+" write-failure-rollback",prior);CheckSeededValues("write-failure rollback");}
 using(var engine=new ExcelEngine((object)app)){engine.CancelAfterWrite=true;try{engine.Apply(engine.Prepare(source),null,null);}catch(InvalidOperationException){}Check(engine.LastOutcome=="rolled-back","Status regression write cancellation did not roll back");CheckStatus(kind+" write-cancel-rollback",prior);CheckSeededValues("write-cancel rollback");}
 using(var engine=new ExcelEngine((object)app)){engine.FailAfterWrites=2;engine.FailRecoveryAt=0;bool recoveryFailed=false;try{engine.Apply(engine.Prepare(source),null,null);}catch(RecoveryException error){recoveryFailed=error.FailedAddresses.Length>0;}Check(recoveryFailed&&engine.RecoveryRequired,"Status regression recovery failure was not reported");CheckStatus(kind+" recovery-failure",prior);}
 }}finally{RestoreStatus(original);}}
 [STAThread]static int Main(string[] args){if(args.Length<2)throw new ArgumentException("ownedPID result-file [--synthetic-regression]");output=Path.GetFullPath(args[1]);string boundary=Path.GetFullPath(Path.Combine(Environment.CurrentDirectory,"artifacts","visible-cells-paste"))+Path.DirectorySeparatorChar;Check(output.StartsWith(boundary,StringComparison.OrdinalIgnoreCase),"Owned result path required");Directory.CreateDirectory(Path.GetDirectoryName(output));var refs=new ComScope();object events=null,calc=null,screen=null,status=null,alerts=null;bool captured=false;try{app=refs.Own((object)ExcelProbe.Attach(Int32.Parse(args[0])));book=refs.Own((object)app.ActiveWorkbook);Check(((string)book.Name).StartsWith("VCP-",StringComparison.Ordinal)&&Path.GetFullPath((string)book.FullName).StartsWith(boundary,StringComparison.OrdinalIgnoreCase),"Owned VCP artifact fixture required");dynamic sheets=refs.Own((object)book.Worksheets);sheet=refs.Own((object)sheets[1]);events=app.EnableEvents;calc=app.Calculation;screen=app.ScreenUpdating;status=app.StatusBar;alerts=app.DisplayAlerts;captured=true;results.Add("  STATUS captured "+StatusDescription(status));sheet.Activate();bool synthetic=args.Length>2&&args[2]=="--synthetic-regression";ClipboardSnapshot clip=synthetic?Source(CellValue.Number(85),CellValue.Text("00123"),CellValue.Empty(),CellValue.Text("한글\n줄바꿈"),CellValue.Empty()):ClipboardReader.ReadSnapshot(Convert.ToInt32((object)app.CutCopyMode));results.Add((synthetic?"Synthetic typed regression items=":"M0 live XML items=")+clip.Items.Count+" kinds="+String.Join(",",System.Linq.Enumerable.Select(clip.Items,x=>x.Kind.ToString()))+" evidence="+clip.Evidence);Console.WriteLine(results[0]);
Test(synthetic?"Typed-five-regression":"M0-clipboard-to-owned-Excel",delegate{R("E2:E6").Select();using(var e=new ExcelEngine(app)){e.Apply(e.Prepare(clip),null,null);Check((double)V("E2")==85,"number");Check((string)V("E3")=="00123","string");Check(V("E4")==null&&V("E6")==null,"empty positions");Check((string)V("E5")=="한글\n줄바꿈","line break");}});
 Test("D01-R02-U01-U15",delegate{SetVisible();string outside=Fingerprint("|$E$2|$E$5|$E$8|");using(var e=new ExcelEngine(app)){var p=e.Prepare(Source(CellValue.Number(85),CellValue.Number(90),CellValue.Number(78)));e.Apply(p,null,null);Check((double)V("E2")==85&&(double)V("E5")==90&&(double)V("E8")==78,"order");Check(outside==Fingerprint("|$E$2|$E$5|$E$8|"),"hidden/outside preservation");e.UndoLast();Check((double)V("E2")==777&&(double)V("E5")==777,"undo");}});
 Test("D04-D05-D06-U16",delegate{R("E2:E4").Select();using(var e=new ExcelEngine(app)){e.Apply(e.Prepare(Source(CellValue.Number(1),CellValue.Number(2),CellValue.Number(3))),null,null);Reject(e,Source(CellValue.Number(7)));e.UndoLast();Check((double)V("E2")==777,"failed validate invalidated prior undo");}});
 Test("D07-D09-D11-D14-D15-D16-U02",delegate{R("E2:E9").Select();R("E2").Formula2="=10+5";using(var e=new ExcelEngine(app)){var p=e.Prepare(Source(CellValue.Empty(),CellValue.Text("00123"),CellValue.Text("12345678901234567890123"),CellValue.Text("=1+1"),CellValue.Text("한글\t😀\n "),CellValue.Error(2042),CellValue.Text("#N/A"),CellValue.Text("")));e.Apply(p,null,null);Check(!(bool)R("E5").HasFormula&&(string)V("E5")=="=1+1","formula injection");Check(ExcelEngine.ReadCell((object)sheet,7,5).Value.Kind==CellValueKind.Error,"error type");e.UndoLast();Check((string)R("E2").Formula2=="=10+5","formula restore");}});
 Test("D03-R08",delegate{R("E5").Select();string before=Fingerprint("|$E$5|");using(var e=new ExcelEngine(app)){e.Apply(e.Prepare(Source(CellValue.Boolean(true))),null,null);}Check((bool)V("E5"),"bool");Check(before==Fingerprint("|$E$5|"),"single SpecialCells bounds");});
 Test("R06-entire-column",delegate{R("E:E").Select();using(var e=new ExcelEngine(app))Reject(e,Source(CellValue.Number(1)));});
 Test("R07-multiple-areas",delegate{Own((object)app.Union(R("E2"),R("E5"))).Select();using(var e=new ExcelEngine(app))Reject(e,Source(CellValue.Number(1),CellValue.Number(2)));});
 Test("R04-zero-visible",delegate{Rows("2:8").Hidden=true;using(var e=new ExcelEngine(app))Reject(e,Source(CellValue.Number(1)));});
 Test("R09-merge",delegate{R("E2:F2").Merge();R("E2").Select();using(var e=new ExcelEngine(app))Reject(e,Source(CellValue.Number(1)));});
 Test("R09-protected",delegate{R("E2").Select();sheet.Protect();try{using(var e=new ExcelEngine(app))Reject(e,Source(CellValue.Number(1)));}finally{sheet.Unprotect();}});
 Test("R10-spill",delegate{R("G2").Formula2="=SEQUENCE(3)";R("G3").Select();using(var e=new ExcelEngine(app))Reject(e,Source(CellValue.Number(1)));});
 Test("R13-validation",delegate{R("E2").Select();Own((object)R("E2").Validation).Add(1,1,1,"1","10");using(var e=new ExcelEngine(app))Reject(e,Source(CellValue.Number(1)));});
 Test("U08-write-failure",delegate{SetVisible();string before=Fingerprint("");using(var e=new ExcelEngine(app)){e.FailAfterWrites=2;bool rejected=false;try{e.Apply(e.Prepare(Source(CellValue.Number(1),CellValue.Number(2),CellValue.Number(3))),null,null);}catch(InvalidOperationException){rejected=true;}Check(rejected&&e.LastOutcome=="rolled-back","failure outcome");Check(before==Fingerprint(""),"rollback");}});
 Test("U09-recovery-failure",delegate{SetVisible();using(var e=new ExcelEngine(app)){e.FailAfterWrites=2;e.FailRecoveryAt=0;bool blocked=false;try{e.Apply(e.Prepare(Source(CellValue.Number(1),CellValue.Number(2),CellValue.Number(3))),null,null);}catch(RecoveryException ex){blocked=ex.FailedAddresses.Length>0;}Check(blocked&&e.RecoveryRequired,"recovery required");Reject(e,Source(CellValue.Number(1),CellValue.Number(2),CellValue.Number(3)));}});
 Test("U11-write-cancel",delegate{SetVisible();string before=Fingerprint("");using(var e=new ExcelEngine(app)){e.CancelAfterWrite=true;try{e.Apply(e.Prepare(Source(CellValue.Number(1),CellValue.Number(2),CellValue.Number(3))),null,null);}catch(InvalidOperationException){}Check(before==Fingerprint(""),"cancel rollback");}});
 Test("U12-original-global-state",delegate{R("E2").Select();app.EnableEvents=false;app.Calculation=-4135;app.ScreenUpdating=false;app.StatusBar="VCP prior";using(var e=new ExcelEngine(app)){e.Apply(e.Prepare(Source(CellValue.Number(1))),null,null);Check(!(bool)app.EnableEvents&&(int)app.Calculation==-4135&&!(bool)app.ScreenUpdating&&(string)app.StatusBar=="VCP prior","globals restored");bool refused=false;try{e.UndoLast();}catch{refused=true;}Check(refused,"disabled events undo unsafe");}app.EnableEvents=true;app.ScreenUpdating=true;app.Calculation=-4105;ExcelEngine.RestoreStatusBar((object)app,false);});
 Test("U12-statusbar-ownership-all-paths",StatusBarOwnershipCase);
 Test("U03-user-edit",delegate{R("E2").Select();using(var e=new ExcelEngine(app)){e.Apply(e.Prepare(Source(CellValue.Number(1))),null,null);R("E2").Value2=42;Application.DoEvents();bool refused=false;try{e.UndoLast();}catch{refused=true;}Check(refused&&(double)V("E2")==42,"edit conflict");}});
 Test("U04-row-insert",delegate{R("E2:E4").Select();using(var e=new ExcelEngine(app)){e.Apply(e.Prepare(Source(CellValue.Number(1),CellValue.Number(1),CellValue.Number(1))),null,null);Rows("2:2").Insert();Application.DoEvents();bool refused=false;try{e.UndoLast();}catch{refused=true;}Check(refused,"row insert conflict");}});
 Test("R11-table-value-R12-mixed",delegate{R("E1").Value2="Data";dynamic tables=Own((object)sheet.ListObjects);dynamic table=Own((object)tables.Add(1,R("E1:E8"),Type.Missing,1));R("E2:E4").Select();using(var e=new ExcelEngine(app)){e.Apply(e.Prepare(Source(CellValue.Number(1),CellValue.Number(2),CellValue.Number(3))),null,null);Check((double)V("E4")==3,"table values");R("E8").Formula2="=1+2";Application.DoEvents();Reject(e,Source(CellValue.Number(1),CellValue.Number(2),CellValue.Number(3)));}table.Unlist();});
  }catch(Exception error){failed++;results.Add("HARNESS FAIL "+error);}finally{if(captured){Cleanup("EnableEvents",delegate{app.EnableEvents=events;});Cleanup("Calculation",delegate{app.Calculation=calc;});Cleanup("ScreenUpdating",delegate{app.ScreenUpdating=screen;});Cleanup("StatusBar",delegate{RestoreStatus(status);});Cleanup("DisplayAlerts",delegate{app.DisplayAlerts=alerts;});}Cleanup("suite references",delegate{refs.Dispose();});sheet=null;book=null;app=null;}results.Add("SUMMARY passed="+passed+" failed="+failed);File.WriteAllLines(output,results,Encoding.UTF8);Console.WriteLine(results[results.Count-1]);return failed==0?0:1;}
}
