using System;using System.IO;using System.Linq;using System.Text;using VisibleCellsPaste;
class OverlapClipboardTests {
[STAThread] static int Main(string[] args){Console.OutputEncoding=new UTF8Encoding(false);var report=new StringBuilder();try{
int pid=int.Parse(args[0]);dynamic app=ExcelProbe.Attach(pid);dynamic book=app.Workbooks[1];if((string)book.Name!="VCP-Filtered.xlsx")throw new Exception("Expected explicit owned synthetic workbook");dynamic sheet=book.Worksheets[1];
uint owner;NativeClipboard.GetWindowThreadProcessId(NativeClipboard.GetClipboardOwner(),out owner);if(owner!=pid)throw new Exception("Owned clipboard required");uint sequence=NativeClipboard.GetClipboardSequenceNumber();var snapshot=ClipboardReader.ReadSnapshot(0);var expected=new[]{CellValue.Number(85),CellValue.Number(90),CellValue.Number(78)};if(snapshot.SourceRows!=1||snapshot.SourceColumns!=3||!snapshot.Items.SequenceEqual(expected))throw new Exception("Expected actual UI H1:J1 copy");
if(sequence!=NativeClipboard.GetClipboardSequenceNumber())throw new Exception("Clipboard changed while reading");report.AppendLine("PASS actual UI horizontal snapshot85/90/78;sequence="+sequence);
sheet.Range["I1:I3"].Select();using(var engine=new ExcelEngine((object)app)){var p=engine.Prepare(snapshot);engine.Apply(p,null,null);for(int i=0;i<3;i++){var state=ExcelEngine.ReadCell((object)sheet,i+1,9);if(state.Formula||!state.Value.Equals(expected[i]))throw new Exception("Overlapping target differs at"+i);}if(!ExcelEngine.ReadValue((object)sheet.Range["H1"].Value2).Equals(CellValue.Number(85))||!ExcelEngine.ReadValue((object)sheet.Range["J1"].Value2).Equals(CellValue.Number(78)))throw new Exception("Outside source sentinels changed");if(!snapshot.Items.SequenceEqual(expected))throw new Exception("Snapshot mutated");report.AppendLine("PASS D20 actual sourceH1:J1 overlap destinationI1:I3; snapshots preserved; source outside targetH1/J1 unchanged");engine.UndoLast();for(int i=0;i<3;i++){var state=ExcelEngine.ReadCell((object)sheet,i+1,9);if(!state.Value.Equals(p.Before[i].Value)||state.Formula!=p.Before[i].Formula||!Object.Equals(state.Format,p.Before[i].Format))throw new Exception("Undo mismatch");}report.AppendLine("PASS U01 overlap immediateUndo restores originalI1:I3");}
report.AppendLine("SUMMARY passed=3 failed=0");return 0;
}catch(Exception e){report.AppendLine("FAIL "+e);return 1;}finally{File.WriteAllText(args[1],report.ToString(),new UTF8Encoding(false));Console.WriteLine(report.ToString());GC.Collect();GC.WaitForPendingFinalizers();}}
}
