using System;
using System.IO;
using System.Reflection;
using System.Windows.Forms;
using VisibleCellsPaste;
class UndoEventProbe {
 static string SortInfo(dynamic sheet){try{dynamic s=sheet.Sort;int n=(int)s.SortFields.Count;string r="none";try{r=(string)s.Rng.Address;}catch(Exception e){r="unavailable:"+e.HResult.ToString("X8");}string fields="";for(int i=1;i<=n;i++){dynamic f=s.SortFields[i];fields+="[key="+f.Key.Address+",order="+f.Order+",on="+f.SortOn+",data="+f.DataOption+"]";}return "Count="+n+" Rng="+r+" Header="+s.Header+" MatchCase="+s.MatchCase+" Orientation="+s.Orientation+" Fields="+fields;}catch(Exception e){return "ERR="+e;}}

 static void Pump(){for(int i=0;i<5;i++){Application.DoEvents();System.Threading.Thread.Sleep(20);}}
 [STAThread] static int Main(string[] args){dynamic app=ExcelProbe.Attach(Int32.Parse(args[0]));dynamic book=app.ActiveWorkbook;if(!((string)book.Name).StartsWith("VCP-"))throw new Exception("Owned workbook required");dynamic sheet=book.Worksheets.Add();sheet.Name="VCP_Probe_"+Guid.NewGuid().ToString("N").Substring(0,8);var log=new System.Collections.Generic.List<string>();object events=app.EnableEvents;try{app.EnableEvents=true;sheet.Range["D2:D4"].Value2=new object[,]{{3},{1},{2}};sheet.Range["E2:E4"].Value2=777.0;sheet.Range["E2:E4"].Select();using(var engine=new ExcelEngine(app)){var epoch=(UndoEpoch)typeof(ExcelEngine).GetField("epoch",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(engine);log.Add("subscribed Available="+epoch.Available+" Version="+epoch.Version+" Suppress="+epoch.Suppress);var source=new ClipboardSnapshot("Synthetic",0,3,1,true,new[]{CellValue.Number(1),CellValue.Number(1),CellValue.Number(1)},"probe");engine.Apply(engine.Prepare(source),null,null);Pump();log.Add("beforeSort "+SortInfo(sheet));log.Add("afterApply Version="+epoch.Version+" Suppress="+epoch.Suppress+" Events="+app.EnableEvents);sheet.Range["D2:E4"].Sort(sheet.Range["D2"],1);Pump();log.Add("afterSort Version="+epoch.Version+" Suppress="+epoch.Suppress+" D2="+sheet.Range["D2"].Value2+" BuiltInUndo="+app.CommandBars.GetEnabledMso("Undo"));log.Add("afterSortMeta "+SortInfo(sheet));sheet.Range["J1"].Value2=42.0;Pump();log.Add("afterOtherEdit Version="+epoch.Version);sheet.Range["E5"].Select();Pump();log.Add("afterSelection Version="+epoch.Version);sheet.Rows["2:2"].Insert();Pump();log.Add("afterRowInsert Version="+epoch.Version);}}finally{app.EnableEvents=events;object alerts=app.DisplayAlerts;try{app.DisplayAlerts=false;sheet.Delete();}finally{app.DisplayAlerts=alerts;ExcelEngine.Release((object)sheet);}}File.WriteAllLines(args[1],log);foreach(string line in log)Console.WriteLine(line);return 0;}
}
